name: Build

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:latest

    steps:
      - uses: actions/checkout@v4
      - name: Build firmware
        shell: bash
        run: |
          . /opt/esp/idf/export.sh
          idf.py build
          mv build/web_server.bin build/app.bin
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.sha }}
          path: |
            build/app.bin
            build/storage.bin
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app.bin
            build/storage.bin
          generate_release_notes: true
